version: 1.0.{build}
before_build:
  - nuget restore SpotifyMuter.sln
after_build:
  - 7z a SpotifyMuter.zip %APPVEYOR_BUILD_FOLDER%\src\SpotifyMuter\bin\%CONFIGURATION%\*.dll
  - 7z a SpotifyMuter.zip %APPVEYOR_BUILD_FOLDER%\src\SpotifyMuter\bin\%CONFIGURATION%\SpotifyMuter.exe
  - 7z a SpotifyMuter.zip %APPVEYOR_BUILD_FOLDER%\src\SpotifyMuter\bin\%CONFIGURATION%\SpotifyMuter.exe.config
build:
  project: SpotifyMuter.sln
  verbosity: minimal
environment:
  matrix:
    - PYTHON: "C:\\Python35-x64"
matrix:
    fast_finish: true
configuration:
  - Debug
  - Release
artifacts:
  - path: SpotifyMuter.zip
    name: SpotifyMuter
deploy:
  description: ''
  provider: GitHub
  auth_token:
    secure: sXlaELnt68veG14jZ7zUMpbH9RUqT8/I1m3KLxkPLqJDa0ZwehcB0hSxFwSQgbQA
  artifact: SpotifyMuter
  draft: true
  prerelease: false
  on:
    configuration: Release
    appveyor_repo_tag: true        # deploy on tag push only